
export BUILDROOT_DIR=${basename ${shell cd ../..; pwd}}
export INCLUDE_FILE= \
  -I../Core/Inc \
  -I../App/Inc \
  -I../../Drivers/STM32H7xx_HAL_Driver/Inc \
  -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy \
  -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include \
  -I../../Drivers/CMSIS/Include \
  -I../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
  -I../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc
